baseURL = 'https://victornovy.com.br/'
languageCode = 'pt-br'
title = 'Victor Novy'

defaultContentLanguage = "pt-br"
defaultColor = "light" # set color mode: dark, light, auto

# Enable emojis globally
enableEmoji = true
ignoreErrors = ["additional-script-loading-error"] # ignore error of loading additional scripts.

[module]
  [[module.imports]]
    path = "github.com/hugo-sid/hugo-blog-awesome"

[[params.socialIcons]]
name = "github"
url = "https://github.com/victornovy"

[[params.socialIcons]]
name = "X"
url = "https://x.com/VictorNovy"

[[params.socialIcons]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/victornovy"

[params]
  goToTop = true

###################################################################

[services]
  [services.googleAnalytics]
    id = 'G-ERX48J4R8D'

###################################################################

############################## Brazilian language ################################
[Languages.pt-br]
  languageName = "Brazilian"
  languageCode = "pt-br"
  contentDir = "content/br"
  weight = 1

  [Languages.pt-br.menu]
  [[Languages.pt-br.menu.main]]
    # The page reference (pageRef) is useful for menu highlighting
    # When pageRef is set, setting `url` is optional; it will be used as a fallback if the page is not found.
    pageRef="/"
    name = 'Início'
    url = '/'
    weight = 10
  [[Languages.pt-br.menu.main]]
    pageRef="posts"
    name = 'Publicações'
    url = '/posts/'
    weight = 20
  [[Languages.pt-br.menu.main]]
    pageRef="about"
    name = 'Sobre'
    url = '/about/'
    weight = 30

[Languages.pt-br.params]
  sitename = "Awesome hugo blog"
  defaultColor = "light" # set color mode: dark, light, auto

  description = "Um tema Hugo veloz e minimalista com suporte a modo claro e escuro para rodar um blog ou site pessoal"
  mainSections = ['posts']
  toc = true # set to false to disable table of contents 'globally'
  tocOpen = false # set to true to open table of contents by default
  goToTop = true # set to false to disable 'go to top' button
  additionalScripts = ['js/custom.js', 'js/custom-2.js']
  dateFormat = "2 January 2006" # date format used to show dates on various pages. If nothing is specified, then "2 Jan 2006" format is used.

  rssFeedDescription = "summary" # available options: 1) summary 2) full

[Languages.pt-br.params.author]
  avatar = "avatar.jpg" # put the file in assets folder; also ensure that image has same height and width
  # Note: image is not rendered if the resource(avatar image) is not found. No error is displayed.
  intro = "Awesome hugo blog"
  name = "Sidharth R"
  description = "Um tema Hugo veloz e minimalista com suporte a modo claro e escuro para rodar um blog ou site pessoal"

# Allow to override webmanifest options
[Languages.pt-br.params.webmanifest]
  name = "sitename" # will use "params.sitename" or "title" by default
  short_name = "sitename" # same as name
  start_url = "/" # will use homepage url by default
  theme_color = "#434648" # default is "#434648" (base color of text). Also will override html `<meta name="theme-color" />`
  background_color = "#fff" # by default depend on "params.defaultColor" for "light" or "auto" will be set to "#fff" for dark will be "#131418" (color of dark mode background)
  display = "standalone"

###################################################################

# Allow to override `browserconfig.xml` params (configuration for windows embedded browsers)
[params.browserconfig]
  TileColor = "#2d89ef" # default windows 10 blue tile color